-- DDL_DESTRUIR.sql

DROP TABLE IF EXISTS `TelefoneVEND`;
DROP TABLE IF EXISTS `enderecoVEND`;
DROP TABLE IF EXISTS `telefoneCli`;
DROP TABLE IF EXISTS `produto_fornecedor`;
DROP TABLE IF EXISTS `formapagamento`;
DROP TABLE IF EXISTS `itempedido`;
DROP TABLE IF EXISTS `pedido`;
DROP TABLE IF EXISTS `vendedor`;
DROP TABLE IF EXISTS `comissao`;
DROP TABLE IF EXISTS `fornecedor`;
DROP TABLE IF EXISTS `estoque`;
DROP TABLE IF EXISTS `roupa`;
DROP TABLE IF EXISTS `enderecoCli`;
DROP TABLE IF EXISTS `cliente`;



